using System.Globalization;
using MainframeEngine.L10n.Gettext;

namespace MainframeEngine.L10n.Extraction;

/// <summary>
/// Collects messages from every extractor into one translation template (<c>.pot</c>): the same message found in
/// several places becomes one entry with all references, extracted comments and flags (what <c>msgcat</c> does).
/// </summary>
internal sealed class TemplateBuilder
{
    private readonly Dictionary<string, PoEntry> _byKey = new(StringComparer.Ordinal);

    /// <summary>Non-fatal problems (plural mismatches), printed by the CLI.</summary>
    public List<string> Warnings { get; } = [];

    public int Count => _byKey.Count;

    public void Add(string? context, string id, string? idPlural, string? reference, string? extractedComment = null, IEnumerable<string>? flags = null)
    {
        ArgumentNullException.ThrowIfNull(id);
        if (id.Length == 0)
            return;
        var entry = new PoEntry { Context = context, Id = id, IdPlural = idPlural };
        if (reference is not null)
            entry.References.Add(reference);
        if (extractedComment is not null)
            entry.ExtractedComments.Add(extractedComment);
        if (flags is not null)
            entry.Flags.AddRange(flags);
        Add(entry);
    }

    /// <summary>Merges a message (from another template, e.g. the C# extractor's).</summary>
    public void Add(PoEntry source)
    {
        ArgumentNullException.ThrowIfNull(source);
        if (source.IsHeader || source.Obsolete)
            return;
        if (!_byKey.TryGetValue(source.Key, out var entry))
        {
            entry = source.CloneTemplate();
            entry.References.Clear();
            entry.ExtractedComments.Clear();
            entry.Flags.Clear();
            _byKey.Add(source.Key, entry);
        }
        else if (source.IdPlural is not null && entry.IdPlural is null)
        {
            entry.IdPlural = source.IdPlural;
        }
        else if (source.IdPlural is not null && entry.IdPlural != source.IdPlural)
        {
            Warnings.Add($"\"{source.Id}\" has two different plurals (\"{entry.IdPlural}\", \"{source.IdPlural}\"); keeping the first");
        }

        foreach (var reference in source.References)
        {
            if (!entry.References.Contains(reference))
                entry.References.Add(reference);
        }

        foreach (var comment in source.ExtractedComments)
        {
            if (!entry.ExtractedComments.Contains(comment))
                entry.ExtractedComments.Add(comment);
        }

        foreach (var flag in source.Flags)
        {
            if (flag != "fuzzy" && !entry.Flags.Contains(flag))
                entry.Flags.Add(flag);
        }
    }

    /// <summary>
    /// The template: header, then messages ordered by their first reference (file, then line), so the file reads in
    /// source order and stays stable between runs.
    /// </summary>
    public PoCatalog Build(string projectName)
    {
        var catalog = new PoCatalog();
        catalog.FileComments.Add($"Translation template for {projectName}.");
        catalog.FileComments.Add("Generated by mf-l10n extract (just l10n-extract); do not edit. Translate the .po files.");
        catalog.SetHeader("Project-Id-Version", projectName);
        catalog.SetHeader("Report-Msgid-Bugs-To", string.Empty);
        catalog.SetHeader("Language", string.Empty);
        catalog.SetHeader("MIME-Version", "1.0");
        catalog.SetHeader("Content-Type", "text/plain; charset=UTF-8");
        catalog.SetHeader("Content-Transfer-Encoding", "8bit");
        catalog.SetHeader("X-Generator", "mf-l10n");

        var entries = _byKey.Values.ToList();
        foreach (var entry in entries)
        {
            entry.References.Sort(CompareReferences);
            entry.Flags.Sort(StringComparer.Ordinal);
        }

        entries.Sort((a, b) =>
        {
            var byReference = (a.References.Count, b.References.Count) switch
            {
                (0, 0) => 0,
                (0, _) => 1,
                (_, 0) => -1,
                _ => CompareReferences(a.References[0], b.References[0]),
            };
            return byReference != 0 ? byReference : string.CompareOrdinal(a.Key, b.Key);
        });
        catalog.Entries.AddRange(entries);
        return catalog;
    }

    /// <summary>Orders <c>path:line</c> references by path, then numerically by line.</summary>
    public static int CompareReferences(string a, string b)
    {
        var (pathA, lineA) = SplitReference(a);
        var (pathB, lineB) = SplitReference(b);
        var byPath = string.CompareOrdinal(pathA, pathB);
        return byPath != 0 ? byPath : lineA.CompareTo(lineB);
    }

    private static (string Path, int Line) SplitReference(string reference)
    {
        var colon = reference.LastIndexOf(':');
        if (colon > 0 && int.TryParse(reference.AsSpan(colon + 1), NumberStyles.None, CultureInfo.InvariantCulture, out var line))
            return (reference[..colon], line);
        return (reference, 0);
    }
}
