#!/usr/bin/env bash
# Maintains Native/natives.lock: the provenance record of the native binaries committed under
# MainframeEngine/runtimes/<rid>/native/.
#
#   Native/natives-lock.sh update [--restamp] [--stamp PATH...]
#                                               rewrite the lock from the binaries currently in runtimes/
#   Native/natives-lock.sh verify               fail if the lock and the committed binaries/sources disagree
#
# Native builds are not bit-reproducible across toolchains, so CI cannot rebuild and compare hashes. Instead each
# component has an "inputs" hash: SHA-256 over its build inputs (CMake files, shim sources, public header, export
# lists) plus the commits of its upstream submodules. Each committed binary records its own SHA-256 and the inputs
# hash it was built from. `verify` fails when
#   - a binary in runtimes/ is missing from the lock, or a locked binary is missing or its SHA-256 differs, or
#   - a binary was built from inputs that no longer match the tree (sources changed, binaries not refreshed).
#
# `update` keeps the recorded inputs hash of binaries whose bytes did not change and stamps new or changed binaries
# with the current inputs hash. `--stamp PATH...` also stamps the given (just rebuilt) binaries as current even if
# their bytes are unchanged (Native/build.sh --stage does this). `--restamp` stamps every binary as current: use it
# only right after copying in a full set of natives.yml artifacts built from the current tree.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
lock_file="$repo_root/Native/natives.lock"
runtimes_dir="MainframeEngine/runtimes"

sha256_file() {
	if command -v sha256sum >/dev/null 2>&1; then
		sha256sum "$1" | cut -d' ' -f1
	else
		shasum -a 256 "$1" | cut -d' ' -f1
	fi
}

sha256_stdin() {
	if command -v sha256sum >/dev/null 2>&1; then
		sha256sum | cut -d' ' -f1
	else
		shasum -a 256 | cut -d' ' -f1
	fi
}

# component -> build-input paths (relative to the repo root; tests and docs are deliberately excluded)
component_inputs() {
	case "$1" in
		enet) echo "Native/CMakeLists.txt Native/ENet/CMakeLists.txt Native/ENet/exports.macos.txt Native/ENet/exports.linux.map" ;;
		mfrmlui) echo "Native/CMakeLists.txt Native/RmlUi/CMakeLists.txt Native/RmlUi/include Native/RmlUi/shim" ;;
		*) return 1 ;;
	esac
}

component_submodules() {
	case "$1" in
		enet) echo "Native/ENet/upstream" ;;
		mfrmlui) echo "Native/RmlUi/external/RmlUi Native/RmlUi/external/freetype" ;;
		*) return 1 ;;
	esac
}

# The commit a submodule gitlink points at in the index (what a fresh checkout builds).
submodule_commit() {
	git -C "$repo_root" ls-files --stage -- "$1" | awk '$1 == "160000" { print $2 }'
}

inputs_hash() {
	local component="$1" path sub
	{
		# shellcheck disable=SC2046
		for path in $(cd "$repo_root" && git ls-files -co --exclude-standard -- $(component_inputs "$component") | LC_ALL=C sort); do
			printf '%s  %s\n' "$(sha256_file "$repo_root/$path")" "$path"
		done
		for sub in $(component_submodules "$component"); do
			printf 'submodule %s %s\n' "$sub" "$(submodule_commit "$sub")"
		done
	} | sha256_stdin
}

component_of() {
	case "$(basename "$1")" in
		enet.dll | libenet.so | libenet.dylib) echo enet ;;
		mfrmlui.dll | libmfrmlui.so | libmfrmlui.dylib) echo mfrmlui ;;
		*) echo "" ;;
	esac
}

list_binaries() {
	(cd "$repo_root" && find "$runtimes_dir" -path '*/native/*' -type f \( -name '*.dll' -o -name '*.so' -o -name '*.dylib' \) 2>/dev/null | LC_ALL=C sort)
}

locked_field() { # locked_field <path> <field-number> : field from the lock's binary line for <path>
	[[ -f "$lock_file" ]] || return 0
	awk -v p="$1" -v f="$2" '$1 == "binary" && $5 == p { print $f }' "$lock_file"
}

cmd_update() {
	local restamp=0
	local stamped=" "
	while [[ $# -gt 0 ]]; do
		case "$1" in
			--restamp) restamp=1; shift ;;
			--stamp)
				shift
				while [[ $# -gt 0 && "$1" != --* ]]; do
					stamped+="${1#"$repo_root"/} "
					shift
				done
				;;
			*) echo "unknown update option: $1" >&2; return 2 ;;
		esac
	done

	local enet_inputs mfrmlui_inputs
	enet_inputs="$(inputs_hash enet)"
	mfrmlui_inputs="$(inputs_hash mfrmlui)"

	local tmp
	tmp="$(mktemp)"
	{
		echo "# Native/natives.lock — provenance of the native binaries committed under $runtimes_dir/<rid>/native/."
		echo "# Generated by Native/natives-lock.sh update; checked by Native/natives-lock.sh verify (natives.yml)."
		echo "# See docs/design/natives.md. Do not edit by hand."
		echo "#"
		echo "# component <name> inputs <sha256 of current build inputs>"
		echo "# submodule <name> <path> <commit>"
		echo "# binary <sha256> <component> <inputs-hash-it-was-built-from> <path>"
		echo
		echo "component enet inputs $enet_inputs"
		for sub in $(component_submodules enet); do echo "submodule enet $sub $(submodule_commit "$sub")"; done
		echo "component mfrmlui inputs $mfrmlui_inputs"
		for sub in $(component_submodules mfrmlui); do echo "submodule mfrmlui $sub $(submodule_commit "$sub")"; done
		echo

		local path component sha old_sha old_inputs current
		while IFS= read -r path; do
			[[ -n "$path" ]] || continue
			component="$(component_of "$path")"
			[[ -n "$component" ]] || continue
			sha="$(sha256_file "$repo_root/$path")"
			if [[ "$component" == enet ]]; then current="$enet_inputs"; else current="$mfrmlui_inputs"; fi
			old_sha="$(locked_field "$path" 2)"
			old_inputs="$(locked_field "$path" 4)"
			if [[ $restamp -eq 0 && "$stamped" != *" $path "* && "$old_sha" == "$sha" && -n "$old_inputs" ]]; then
				echo "binary $sha $component $old_inputs $path"
			else
				echo "binary $sha $component $current $path"
			fi
		done < <(list_binaries)
	} > "$tmp"
	mv "$tmp" "$lock_file"
	echo "updated $lock_file"
}

cmd_verify() {
	local failures=0
	if [[ ! -f "$lock_file" ]]; then
		echo "FAIL: $lock_file not found" >&2
		return 1
	fi

	local component expected locked
	for component in enet mfrmlui; do
		expected="$(inputs_hash "$component")"
		locked="$(awk -v c="$component" '$1 == "component" && $2 == c { print $4 }' "$lock_file")"
		if [[ "$expected" != "$locked" ]]; then
			echo "NOTE: $component build inputs changed since the lock was written (lock $locked, tree $expected)."
		fi
	done

	local path sha recorded_sha recorded_component recorded_inputs current
	while IFS= read -r path; do
		[[ -n "$path" ]] || continue
		component="$(component_of "$path")"
		[[ -n "$component" ]] || continue
		recorded_sha="$(locked_field "$path" 2)"
		if [[ -z "$recorded_sha" ]]; then
			echo "FAIL: $path is not listed in natives.lock (run Native/natives-lock.sh update)" >&2
			failures=$((failures + 1))
		fi
	done < <(list_binaries)

	while read -r _ recorded_sha recorded_component recorded_inputs path; do
		if [[ ! -f "$repo_root/$path" ]]; then
			echo "FAIL: locked binary $path is missing" >&2
			failures=$((failures + 1))
			continue
		fi
		sha="$(sha256_file "$repo_root/$path")"
		if [[ "$sha" != "$recorded_sha" ]]; then
			echo "FAIL: $path sha256 $sha does not match natives.lock ($recorded_sha)" >&2
			failures=$((failures + 1))
		fi
		current="$(inputs_hash "$recorded_component")"
		if [[ "$recorded_inputs" != "$current" ]]; then
			echo "FAIL: $path was built from stale $recorded_component inputs; rebuild with natives.yml and refresh" >&2
			failures=$((failures + 1))
		else
			echo "ok   $path"
		fi
	done < <(awk '$1 == "binary"' "$lock_file")

	if [[ $failures -gt 0 ]]; then
		echo "natives.lock verification failed ($failures problem(s)). See docs/design/natives.md." >&2
		return 1
	fi
	echo "natives.lock verified"
}

case "${1:-}" in
	update) shift; cmd_update "$@" ;;
	verify) cmd_verify ;;
	*) echo "usage: $0 update [--restamp] [--stamp PATH...] | verify" >&2; exit 2 ;;
esac
