<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationIcon>Content\Branding\mg_300_circle.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MainframeEngine\MainframeEngine.csproj" />
    </ItemGroup>

    <!-- Copy everything in content folder to build destination -->
    <ItemGroup>
        <None Update="Content\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Content\SpineBoy\spineboy-pro.atlas">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Content\SpineBoy\spineboy-pro.json">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Content\SpineBoy\spineboy-pro.png">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
