using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace MainframeEngine.Generators;

/// <summary>
/// Emits one file per assembly: a <c>[ModuleInitializer]</c> that registers a <c>NodeTypeInfo</c> for every
/// node and resource type, with typed property accessors, signal add/remove accessors and migrations.
/// </summary>
internal static class RegistrationEmitter
{
    private const string Ser = "global::MainframeEngine.Serialization";

    public static void Emit(SourceProductionContext context, ImmutableArray<TypeModel> models, string assemblyName)
    {
        var unique = models
            .GroupBy(m => m.FullName)
            .Select(g => g.First())
            .OrderBy(m => m.FullName, System.StringComparer.Ordinal)
            .ToList();

        foreach (var model in unique)
            foreach (var diagnostic in model.Diagnostics)
                context.ReportDiagnostic(diagnostic.ToDiagnostic());

        var registrable = unique.Where(m => !m.Diagnostics.Any(d => d.Id == Diagnostics.TypeNotAccessible.Id)).ToList();
        foreach (var duplicate in registrable.GroupBy(m => m.TypeName).Where(g => g.Count() > 1))
            foreach (var model in duplicate)
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.DuplicateTypeName, model.Location?.ToLocation(),
                    model.TypeName, string.Join(", ", duplicate.Select(m => m.FullName))));

        if (registrable.Count == 0)
            return;

        context.AddSource("MainframeEngine.TypeRegistration.g.cs", Generate(registrable, assemblyName));
    }

    internal static string Generate(IReadOnlyList<TypeModel> models, string assemblyName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> by MainframeEngine.Generators: node and resource type registration.");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("namespace MainframeEngine.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"MainframeEngine.Generators\", \"1.0\")]");
        sb.AppendLine($"    internal static class TypeRegistration_{Sanitize(assemblyName)}");
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Register()");
        sb.AppendLine("        {");
        foreach (var model in models)
            EmitType(sb, model);
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitType(StringBuilder sb, TypeModel m)
    {
        const string i1 = "            ";
        const string i2 = "                ";
        const string i3 = "                    ";

        sb.AppendLine($"{i1}{Ser}.TypeRegistry.Register(new {Ser}.NodeTypeInfo(");
        sb.AppendLine($"{i2}name: {Literal(m.TypeName)},");
        sb.AppendLine($"{i2}type: typeof({m.FullName}),");
        sb.AppendLine($"{i2}baseType: {(m.BaseType is null ? "null" : $"typeof({m.BaseType})")},");
        sb.AppendLine($"{i2}factory: {(m.HasFactory ? $"static () => new {m.FullName}()" : "null")},");

        sb.AppendLine($"{i2}properties: new {Ser}.ExportPropertyInfo[]");
        sb.AppendLine($"{i2}{{");
        foreach (var e in m.Exports)
        {
            var member = TypeModelBuilder.Identifier(e.Name);
            sb.AppendLine($"{i3}new {Ser}.ExportPropertyInfo<{m.FullName}, {e.ValueType}>(");
            sb.AppendLine($"{i3}    {Literal(e.Name)},");
            sb.AppendLine($"{i3}    static o => o.{member},");
            sb.AppendLine($"{i3}    static (o, v) => o.{member} = v,");
            sb.AppendLine($"{i3}    {e.CodecExpression},");
            sb.AppendLine($"{i3}    {Hints(e)},");
            sb.AppendLine($"{i3}    {(e.Group is null ? "null" : Literal(e.Group))}),");
        }

        sb.AppendLine($"{i2}}},");

        sb.AppendLine($"{i2}signals: new {Ser}.SignalInfo[]");
        sb.AppendLine($"{i2}{{");
        foreach (var s in m.Signals)
        {
            var member = TypeModelBuilder.Identifier(s.Name);
            var types = string.Join(", ", s.ParameterTypes.Select(t => $"typeof({t})"));
            sb.AppendLine($"{i3}new {Ser}.SignalInfo(");
            sb.AppendLine($"{i3}    {Literal(s.Name)},");
            sb.AppendLine($"{i3}    typeof({s.DelegateType}),");
            sb.AppendLine($"{i3}    new global::System.Type[] {{ {types} }},");
            sb.AppendLine($"{i3}    static (o, d) => (({m.FullName})o).{member} += ({s.DelegateType})d,");
            sb.AppendLine($"{i3}    static (o, d) => (({m.FullName})o).{member} -= ({s.DelegateType})d,");
            sb.AppendLine($"{i3}    {Forwarder(s)}),");
        }

        sb.AppendLine($"{i2}}},");

        sb.AppendLine($"{i2}migrations: new {Ser}.MigrationInfo[]");
        sb.AppendLine($"{i2}{{");
        foreach (var mig in m.Migrations)
            sb.AppendLine($"{i3}new {Ser}.MigrationInfo({mig.FromVersion}, static p => {m.FullName}.{TypeModelBuilder.Identifier(mig.MethodName)}(p)),");
        sb.AppendLine($"{i2}}},");

        sb.AppendLine($"{i2}version: {m.Version},");
        var traits = new List<string> { $"{Ser}.NodeTypeTraits.{m.Kind}" };
        if (m.IsTool)
            traits.Add($"{Ser}.NodeTypeTraits.Tool");
        if (m.IsAbstract)
            traits.Add($"{Ser}.NodeTypeTraits.Abstract");
        sb.Append($"{i2}flags: {string.Join(" | ", traits)}");
        if (m.Icon is not null)
            sb.Append($",\n{i2}icon: {Literal(m.Icon)}");
        if (m.IconFamily != 0)
            sb.Append($",\n{i2}iconFamily: (global::MainframeEngine.EditorIconFamily){m.IconFamily}");
        if (m.Description is not null)
            sb.Append($",\n{i2}description: {Literal(m.Description)}");
        sb.AppendLine("));");
    }

    private static string Forwarder(SignalModel s)
    {
        if (!s.CanForward)
            return "null";
        var args = string.Join(", ", Enumerable.Range(0, s.ParameterTypes.Count).Select(i => $"a{i}"));
        return $"static sink => ({s.DelegateType})(({args}) => sink(new object[] {{ {args} }}))";
    }

    private static string Hints(ExportModel e)
    {
        var parts = new List<string>();
        if (e.Range is not null)
            parts.Add($"Range = {Literal(e.Range)}");
        if (e.File is not null)
            parts.Add($"File = {Literal(e.File)}");
        if (e.Directory)
            parts.Add("Directory = true");
        if (e.Multiline)
            parts.Add("Multiline = true");
        if (e.Flags)
            parts.Add("Flags = true");
        if (e.NodeType is not null)
            parts.Add($"NodeType = typeof({e.NodeType})");
        if (e.Translatable)
            parts.Add("Translatable = true");
        if (e.Icon is not null)
            parts.Add($"Icon = {Literal(e.Icon)}");
        if (e.Description is not null)
            parts.Add($"Description = {Literal(e.Description)}");
        return parts.Count == 0 ? "null" : $"new {Ser}.ExportHints {{ {string.Join(", ", parts)} }}";
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Sanitize(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        return sb.ToString();
    }
}
