using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace MainframeEngine.Generators;

/// <summary>
/// Emits the networking half of a node type (docs/design/networking.md#replication): for every type with
/// <c>[Replicated]</c> members or <c>[Rpc]</c> methods, a <c>ReplicatedState</c> subclass with one typed shadow
/// field per member (change detection, snapshot write/read, interpolation buffers), a <c>ReplicationTypeInfo</c>
/// with typed RPC dispatchers, a per-assembly <c>[ModuleInitializer]</c> registering them with
/// <c>ReplicationRegistry</c>, and <c>Rpc&lt;Method&gt;</c> / <c>Rpc&lt;Method&gt;To</c> extension methods that send
/// the calls. Everything is typed at compile time: no reflection, boxing or allocation on the network tick.
/// </summary>
internal static class ReplicationEmitter
{
    private const string Net = "global::MainframeEngine.Networking";
    private const string Codec = Net + ".NetCodec";

    public static void Emit(SourceProductionContext context, ImmutableArray<TypeModel> models, string assemblyName)
    {
        var networked = models
            .GroupBy(m => m.FullName)
            .Select(g => g.First())
            .Where(m => m.HasNetworking && !m.Diagnostics.Any(d => d.Id == Diagnostics.TypeNotAccessible.Id))
            .OrderBy(m => m.FullName, System.StringComparer.Ordinal)
            .ToList();

        if (networked.Count == 0)
            return;

        context.AddSource("MainframeEngine.Replication.g.cs", Generate(networked, assemblyName));
    }

    internal static string Generate(IReadOnlyList<TypeModel> models, string assemblyName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> by MainframeEngine.Generators: [Replicated] state and [Rpc] dispatch.");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("namespace MainframeEngine.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"MainframeEngine.Generators\", \"1.0\")]");
        sb.AppendLine($"    internal static class ReplicationRegistration_{Sanitize(assemblyName)}");
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Register()");
        sb.AppendLine("        {");
        foreach (var model in models)
            sb.AppendLine($"            {Net}.ReplicationRegistry.Register({StateClass(model)}.Info);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        foreach (var model in models)
            EmitState(sb, model);
        sb.AppendLine("}");

        foreach (var model in models.Where(m => m.Rpcs.Count > 0))
            EmitRpcExtensions(sb, model);

        return sb.ToString();
    }

    internal static string StateClass(TypeModel model) => "Replication_" + Sanitize(model.FullName.Replace("global::", ""));

    private static void EmitState(StringBuilder sb, TypeModel m)
    {
        const string i2 = "        ";
        const string i3 = "            ";
        const string i4 = "                ";
        var cls = StateClass(m);
        var props = m.Replicated.Items;
        var hasState = props.Length > 0;

        sb.AppendLine();
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"MainframeEngine.Generators\", \"1.0\")]");
        sb.AppendLine($"    internal sealed class {cls} : {Net}.ReplicatedState");
        sb.AppendLine("    {");

        // Type info: properties, RPC dispatchers, state factory.
        sb.AppendLine($"{i2}public static readonly {Net}.ReplicationTypeInfo Info = new {Net}.ReplicationTypeInfo(");
        sb.AppendLine($"{i3}type: typeof({m.FullName}),");
        sb.AppendLine($"{i3}schemaHash: 0x{SchemaHash(m).ToString("X8", CultureInfo.InvariantCulture)}u,");
        sb.AppendLine($"{i3}properties: new {Net}.ReplicatedPropertyInfo[]");
        sb.AppendLine($"{i3}{{");
        foreach (var p in props)
            sb.AppendLine($"{i4}new {Net}.ReplicatedPropertyInfo({Literal(p.Value.Name)}, typeof({p.Value.Type}), {Bool(p.Interpolate)}),");
        sb.AppendLine($"{i3}}},");
        sb.AppendLine($"{i3}rpcs: new {Net}.RpcInfo[]");
        sb.AppendLine($"{i3}{{");
        foreach (var rpc in m.Rpcs)
        {
            var parameterTypes = string.Join(", ", rpc.Parameters.Select(p => $"typeof({p.Type})"));
            sb.AppendLine($"{i4}new {Net}.RpcInfo({Literal(rpc.Name)}, (global::MainframeEngine.RpcMode){rpc.Mode}, {Bool(rpc.Reliable)}, {Bool(rpc.CallLocal)},");
            sb.AppendLine($"{i4}    new global::System.Type[] {{ {parameterTypes} }},");
            sb.AppendLine($"{i4}    static (global::MainframeEngine.Node __mfNode, {Net}.NetBufferReader __mfReader) =>");
            sb.AppendLine($"{i4}    {{");
            var args = new List<string>();
            for (var a = 0; a < rpc.Parameters.Count; a++)
            {
                var name = "a" + a.ToString(CultureInfo.InvariantCulture);
                sb.AppendLine($"{i4}        {ReadStatement(rpc.Parameters.Items[a], name, "__mfReader")}");
                args.Add(name);
            }

            sb.AppendLine($"{i4}        (({m.FullName})__mfNode).{TypeModelBuilder.Identifier(rpc.Name)}({string.Join(", ", args)});");
            sb.AppendLine($"{i4}    }}),");
        }

        sb.AppendLine($"{i3}}},");
        sb.AppendLine($"{i3}createState: {(hasState ? $"static () => new {cls}()" : "null")});");

        if (!hasState)
        {
            sb.AppendLine();
            sb.AppendLine($"{i2}private {cls}() : base(0) {{ }}");
            EmitEmptyOverrides(sb);
            sb.AppendLine("    }");
            return;
        }

        // Shadow fields: the last captured (server) or received (client) value of every member.
        sb.AppendLine();
        for (var i = 0; i < props.Length; i++)
        {
            sb.AppendLine($"{i2}private {props[i].Value.Type} _v{i};");
            if (props[i].Interpolate)
                sb.AppendLine($"{i2}private readonly {Net}.InterpolationBuffer<{props[i].Value.Type}> _b{i} = new {Net}.InterpolationBuffer<{props[i].Value.Type}>();");
        }

        var interpolated = props.Select((p, i) => (p, i)).Where(x => x.p.Interpolate).ToList();

        sb.AppendLine();
        sb.AppendLine($"{i2}public {cls}() : base({props.Length}) {{ }}");
        sb.AppendLine();
        sb.AppendLine($"{i2}public override bool HasInterpolation => {Bool(interpolated.Count > 0)};");

        // Capture: compare with the shadow, record the tick of each change.
        sb.AppendLine();
        sb.AppendLine($"{i2}public override void Capture(global::MainframeEngine.Node node, uint tick)");
        sb.AppendLine($"{i2}{{");
        sb.AppendLine($"{i3}var o = ({m.FullName})node;");
        for (var i = 0; i < props.Length; i++)
        {
            var p = props[i].Value;
            sb.AppendLine($"{i3}{{");
            sb.AppendLine($"{i4}var v = o.{TypeModelBuilder.Identifier(p.Name)};");
            sb.AppendLine($"{i4}if (!global::System.Collections.Generic.EqualityComparer<{p.Type}>.Default.Equals(_v{i}, v))");
            sb.AppendLine($"{i4}{{");
            sb.AppendLine($"{i4}    _v{i} = v;");
            sb.AppendLine($"{i4}    MarkChanged({i}, tick);");
            sb.AppendLine($"{i4}}}");
            sb.AppendLine($"{i3}}}");
        }

        sb.AppendLine($"{i2}}}");

        // Write: the captured values whose bit is set.
        sb.AppendLine();
        sb.AppendLine($"{i2}public override void Write({Net}.NetBufferWriter writer, ulong mask)");
        sb.AppendLine($"{i2}{{");
        for (var i = 0; i < props.Length; i++)
            sb.AppendLine($"{i3}if ((mask & {Bit(i)}) != 0) {WriteStatement(props[i].Value, $"_v{i}", "writer")}");
        sb.AppendLine($"{i2}}}");

        // Read: apply (or buffer for interpolation) the values whose bit is set.
        sb.AppendLine();
        sb.AppendLine($"{i2}public override void Read({Net}.NetBufferReader reader, global::MainframeEngine.Node node, ulong mask, in {Net}.ReplicationReadContext context)");
        sb.AppendLine($"{i2}{{");
        sb.AppendLine($"{i3}var o = ({m.FullName})node;");
        for (var i = 0; i < props.Length; i++)
        {
            var p = props[i].Value;
            var member = TypeModelBuilder.Identifier(p.Name);
            sb.AppendLine($"{i3}if ((mask & {Bit(i)}) != 0)");
            sb.AppendLine($"{i3}{{");
            sb.AppendLine($"{i4}{ReadStatement(p, "v", "reader")}");
            sb.AppendLine($"{i4}_v{i} = v;");
            if (props[i].Interpolate)
            {
                sb.AppendLine($"{i4}_b{i}.Push(context.Tick, v, context.PreviousTick);");
                sb.AppendLine($"{i4}if (context.ApplyDirectly) o.{member} = v;");
            }
            else
            {
                sb.AppendLine($"{i4}o.{member} = v;");
            }

            sb.AppendLine($"{i3}}}");
        }

        sb.AppendLine($"{i2}}}");

        // Interpolate: sample every buffer at the render time.
        sb.AppendLine();
        sb.AppendLine($"{i2}public override void Interpolate(global::MainframeEngine.Node node, in {Net}.InterpolationTime time)");
        sb.AppendLine($"{i2}{{");
        if (interpolated.Count > 0)
        {
            sb.AppendLine($"{i3}var o = ({m.FullName})node;");
            foreach (var (p, i) in interpolated)
            {
                sb.AppendLine($"{i3}if (_b{i}.Sample(in time, out var from{i}, out var to{i}, out var t{i}))");
                sb.AppendLine($"{i4}o.{TypeModelBuilder.Identifier(p.Value.Name)} = {Net}.NetLerp.Lerp(from{i}, to{i}, t{i});");
            }
        }

        sb.AppendLine($"{i2}}}");

        sb.AppendLine();
        sb.AppendLine($"{i2}public override void ClearInterpolation()");
        sb.AppendLine($"{i2}{{");
        foreach (var (_, i) in interpolated)
            sb.AppendLine($"{i3}_b{i}.Clear();");
        sb.AppendLine($"{i2}}}");
        sb.AppendLine("    }");
    }

    private static void EmitEmptyOverrides(StringBuilder sb)
    {
        const string i2 = "        ";
        sb.AppendLine($"{i2}public override bool HasInterpolation => false;");
        sb.AppendLine($"{i2}public override void Capture(global::MainframeEngine.Node node, uint tick) {{ }}");
        sb.AppendLine($"{i2}public override void Write({Net}.NetBufferWriter writer, ulong mask) {{ }}");
        sb.AppendLine($"{i2}public override void Read({Net}.NetBufferReader reader, global::MainframeEngine.Node node, ulong mask, in {Net}.ReplicationReadContext context) {{ }}");
        sb.AppendLine($"{i2}public override void Interpolate(global::MainframeEngine.Node node, in {Net}.InterpolationTime time) {{ }}");
        sb.AppendLine($"{i2}public override void ClearInterpolation() {{ }}");
    }

    private static void EmitRpcExtensions(StringBuilder sb, TypeModel m)
    {
        var info = $"global::MainframeEngine.Generated.{StateClass(m)}.Info";
        var classAccess = m.IsPublic ? "public" : "internal";
        var indent = m.Namespace is null ? "" : "    ";

        sb.AppendLine();
        if (m.Namespace is not null)
        {
            sb.AppendLine($"namespace {m.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"{indent}/// <summary>Sends the <c>[Rpc]</c> methods of <see cref=\"{m.FullName.Replace("global::", "")}\"/> (generated).</summary>");
        sb.AppendLine($"{indent}[global::System.CodeDom.Compiler.GeneratedCode(\"MainframeEngine.Generators\", \"1.0\")]");
        sb.AppendLine($"{indent}{classAccess} static class {m.FlatName}RpcExtensions");
        sb.AppendLine($"{indent}{{");
        for (var r = 0; r < m.Rpcs.Count; r++)
        {
            var rpc = m.Rpcs.Items[r];
            var access = m.IsPublic && rpc.IsPublic ? "public" : "internal";
            var parameters = string.Concat(rpc.Parameters.Select(p => $", {p.Type} {TypeModelBuilder.Identifier(p.Name)}"));
            var arguments = string.Join(", ", rpc.Parameters.Select(p => TypeModelBuilder.Identifier(p.Name)));
            var method = TypeModelBuilder.Identifier(rpc.Name);

            foreach (var targeted in new[] { false, true })
            {
                var name = targeted ? $"Rpc{rpc.Name}To" : $"Rpc{rpc.Name}";
                // Generated locals use reserved "__mf" names so no RPC parameter name can collide with them.
                var target = targeted ? $", {Net}.PeerId __mfPeer" : "";
                sb.AppendLine();
                sb.AppendLine(targeted
                    ? $"{indent}    /// <summary>Calls <c>{rpc.Name}</c> on one peer (the server calls a client; a client may only target the server).</summary>"
                    : $"{indent}    /// <summary>Calls <c>{rpc.Name}</c> remotely: on every client from the server, on the server from a client.</summary>");
                sb.AppendLine($"{indent}    {access} static void {name}(this {m.FullName} __mfNode{target}{parameters})");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        var __mfRpc = {info}.Rpcs[{r}];");
                sb.AppendLine(targeted
                    ? $"{indent}        var __mfCall = {Net}.MultiplayerApi.BeginRpc(__mfNode, __mfRpc, __mfPeer);"
                    : $"{indent}        var __mfCall = {Net}.MultiplayerApi.BeginRpc(__mfNode, __mfRpc);");
                sb.AppendLine($"{indent}        if (__mfCall.Writer is {{ }} __mfWriter)");
                sb.AppendLine($"{indent}        {{");
                foreach (var p in rpc.Parameters)
                    sb.AppendLine($"{indent}            {WriteStatement(p, TypeModelBuilder.Identifier(p.Name), "__mfWriter")}");
                sb.AppendLine($"{indent}            {Net}.MultiplayerApi.EndRpc(in __mfCall);");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        if (__mfCall.InvokeLocally)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            var __mfPrevious = {Net}.MultiplayerApi.BeginLocalCall(in __mfCall);");
                sb.AppendLine($"{indent}            try {{ __mfNode.{method}({arguments}); }}");
                sb.AppendLine($"{indent}            finally {{ {Net}.MultiplayerApi.EndLocalCall(in __mfCall, __mfPrevious); }}");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
            }
        }

        sb.AppendLine($"{indent}}}");
        if (m.Namespace is not null)
            sb.AppendLine("}");
    }

    private static string WriteStatement(NetValueModel value, string expression, string writer) => value.Kind switch
    {
        NetCodecKind.Enum => $"{Codec}.Write({writer}, ({value.UnderlyingType}){expression});",
        NetCodecKind.Transferable => $"{Codec}.WriteValue({writer}, in {expression});",
        _ => $"{Codec}.Write({writer}, {expression});",
    };

    private static string ReadStatement(NetValueModel value, string variable, string reader) => value.Kind switch
    {
        NetCodecKind.Enum => $"{Codec}.Read({reader}, out {value.UnderlyingType} {variable}Raw); var {variable} = ({value.Type}){variable}Raw;",
        NetCodecKind.Transferable => $"{Codec}.ReadValue({reader}, out {value.Type} {variable});",
        _ => $"{Codec}.Read({reader}, out {value.Type} {variable});",
    };

    /// <summary>
    /// FNV-1a over the type's network shape (members, their types and interpolation, RPC signatures and flags), so
    /// <c>ReplicationRegistry.Fingerprint</c> differs whenever two builds would disagree on the wire.
    /// </summary>
    internal static uint SchemaHash(TypeModel m)
    {
        var text = new StringBuilder(m.FullName).Append('|');
        foreach (var p in m.Replicated)
            text.Append("P:").Append(p.Value.Name).Append(':').Append(p.Value.Type).Append(':').Append(p.Interpolate ? '1' : '0').Append('|');
        foreach (var r in m.Rpcs)
        {
            text.Append("R:").Append(r.Name).Append(':').Append(r.Mode).Append(':').Append(r.Reliable ? '1' : '0')
                .Append(r.CallLocal ? '1' : '0').Append('(');
            foreach (var p in r.Parameters)
                text.Append(p.Type).Append(',');
            text.Append(")|");
        }

        var hash = 2166136261u;
        foreach (var c in text.ToString())
            hash = unchecked((hash ^ c) * 16777619u);
        return hash;
    }

    private static string Bit(int index) => $"(1UL << {index})";

    private static string Bool(bool value) => value ? "true" : "false";

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Sanitize(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        return sb.ToString();
    }
}
