// <auto-generated>
// Fitted by Examples/Forest/Tools/grade_from_shots.py from ungraded renders of the reference shots (ADR 0175); do not edit.
// Measured: p5 0.181, p50 0.377, p95 0.644; foliage saturation 0.385 (51 % of pixels); shade chroma [-0.022, 0.0135, -0.0695], light chroma [-0.0023, 0.006, -0.0524].
// </auto-generated>
namespace Forest;

/// <summary>The forest-morning grade's numbers fitted to the R1–R7 renders (<see cref="ForestGrade"/> applies them).</summary>
internal static class ForestGradeFit
{
    /// <summary>The tone curve's control points (display in → out): the shots' p5, p50 and p95 luminance to the targets.</summary>
    public static readonly float[] CurveX = [0.0000f, 0.1806f, 0.3769f, 0.6444f, 1.0000f];

    public static readonly float[] CurveY = [0.0300f, 0.1470f, 0.3640f, 0.7860f, 0.9750f];

    /// <summary>Scales the foliage's saturation towards a natural green.</summary>
    public const float FoliageSaturation = 1.1000f;

    /// <summary>How far the foliage's hue moves towards olive (0–1).</summary>
    public const float FoliageWarmth = 0.5000f;

    /// <summary>Added to the shade (rgb), moving its cast halfway to a faintly cool green.</summary>
    public static readonly System.Numerics.Vector3 ShadeTint = new(0.0128f, -0.0034f, -0.0037f);

    /// <summary>Added to the light (rgb), moving its cast halfway to a warm low sun.</summary>
    public static readonly System.Numerics.Vector3 LightTint = new(0.0047f, 0.0045f, -0.0400f);
}
