// <auto-generated>
// Fitted by Examples/Forest/Tools/grade_from_shots.py from ungraded renders of the reference shots (ADR 0175); do not edit.
// Measured: p5 0.084, p50 0.249, p95 0.802; foliage saturation 0.619 (63 % of pixels); shade chroma [-0.0303, 0.0178, -0.0871], light chroma [0.0207, 0.0142, -0.2012].
// </auto-generated>
namespace Forest;

/// <summary>The forest-morning grade's numbers fitted to the R1–R7 renders (<see cref="ForestGrade"/> applies them).</summary>
internal static class ForestGradeFit
{
    /// <summary>The tone curve's control points (display in → out): the shots' p5, p50 and p95 luminance to the targets.</summary>
    public static readonly float[] CurveX = [0.0000f, 0.0840f, 0.2491f, 0.8018f, 1.0000f];

    public static readonly float[] CurveY = [0.0120f, 0.0450f, 0.2550f, 0.8200f, 0.9750f];

    /// <summary>Scales the foliage's saturation towards a natural green.</summary>
    public const float FoliageSaturation = 0.8200f;

    /// <summary>How far the foliage's hue moves towards olive (0–1).</summary>
    public const float FoliageWarmth = 0.5000f;

    /// <summary>Added to the shade (rgb), moving its cast halfway to a faintly cool green.</summary>
    public static readonly System.Numerics.Vector3 ShadeTint = new(0.0122f, -0.0069f, 0.0300f);

    /// <summary>Added to the light (rgb), moving its cast halfway to a warm low sun.</summary>
    public static readonly System.Numerics.Vector3 LightTint = new(0.0047f, -0.0011f, 0.0400f);
}
