using System.Globalization;
using System.Text;
using MainframeEngine.L10n.Gettext;
using MainframeEngine.Localization;

namespace MainframeEngine.L10n;

/// <summary>Which accented letters the pseudo-locale uses.</summary>
internal enum PseudoCharset
{
    /// <summary>Every ASCII letter gets an accented look-alike (Latin Extended-A/B and beyond).</summary>
    Full,

    /// <summary>
    /// Only letters with a Latin-1 accented form (vowels, c, n, y, d); renders with fonts limited to Latin-1, such as
    /// simple bitmap fonts.
    /// </summary>
    Latin1,
}

/// <summary>
/// Generates the <c>qps</c> pseudo-locale: <c>Settings</c> → <c>[Šéţţîñĝš ~~]</c>. Accents show missing glyphs and
/// encoding bugs, the ~30% padding shows truncation, the brackets show clipping and every string that bypasses
/// translation (it appears without brackets).
/// </summary>
internal static class PseudoLocalizer
{
    private const string FullFrom = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    private const string FullTo = "ÅƁÇÐÉƑĜĤÎĴĶĻṀÑÖÞǪŔŠŢÛṼŴẊÝŽåƀçðéƒĝĥîĵķļṁñöþǫŕšţûṽŵẋýž";
    private const string Latin1From = "ACDEINOUYacdeinouy";
    private const string Latin1To = "ÅÇÐÉÎÑÖÛÝåçðéîñöûý";

    /// <summary>
    /// Transforms one message. Format items (<c>{0}</c>, <c>{1:N2}</c>), escaped braces, RmlUi data expressions
    /// (<c>{{ score }}</c>), <c>%</c>-sequences and whitespace at either end are kept as they are.
    /// </summary>
    public static string Transform(string text, PseudoCharset charset = PseudoCharset.Full, double expansion = 0.3)
    {
        ArgumentNullException.ThrowIfNull(text);
        if (text.Length == 0)
            return text;
        var (from, to) = charset == PseudoCharset.Full ? (FullFrom, FullTo) : (Latin1From, Latin1To);

        var start = 0;
        while (start < text.Length && char.IsWhiteSpace(text[start]))
            start++;
        var end = text.Length;
        while (end > start && char.IsWhiteSpace(text[end - 1]))
            end--;

        var sb = new StringBuilder(text.Length * 2);
        sb.Append(text, 0, start).Append('[');
        var letters = 0;
        var i = start;
        while (i < end)
        {
            var c = text[i];
            if (c == '{')
            {
                var close = text[i..end].StartsWith("{{", StringComparison.Ordinal)
                    ? IndexOfClose(text, i + 2, end, "}}")
                    : IndexOfClose(text, i + 1, end, "}");
                if (close > i)
                {
                    sb.Append(text, i, close - i);
                    i = close;
                    continue;
                }
            }

            if (c == '%' && i + 1 < end && (char.IsAsciiLetter(text[i + 1]) || text[i + 1] == '%'))
            {
                sb.Append(text, i, 2);
                i += 2;
                continue;
            }

            var mapped = from.IndexOf(c, StringComparison.Ordinal);
            sb.Append(mapped >= 0 ? to[mapped] : c);
            if (char.IsLetterOrDigit(c))
                letters++;
            i++;
        }

        var padding = (int)Math.Ceiling(letters * expansion);
        if (padding > 0)
            sb.Append(' ').Append('~', Math.Max(padding - 1, 1));
        sb.Append(']').Append(text, end, text.Length - end);
        return sb.ToString();
    }

    // Index just past the terminator, or -1.
    private static int IndexOfClose(string text, int from, int end, string terminator)
    {
        var at = text.IndexOf(terminator, from, end - from, StringComparison.Ordinal);
        if (terminator == "}" && at >= 0 && at + 1 < end && text[at + 1] == '}')
            return at + 2;
        return at < 0 ? -1 : at + terminator.Length;
    }

    /// <summary>A complete <c>qps</c> <c>.po</c> catalog for a template: every message translated.</summary>
    public static PoCatalog CreateCatalog(PoCatalog template, PseudoCharset charset = PseudoCharset.Full, double expansion = 0.3)
    {
        ArgumentNullException.ThrowIfNull(template);
        var catalog = new PoCatalog();
        catalog.FileComments.Add("Pseudo-locale generated by mf-l10n pseudo from the translation template. Do not edit.");
        catalog.SetHeader("Project-Id-Version", template.GetHeader("Project-Id-Version") ?? "PACKAGE VERSION");
        catalog.SetHeader("Language", LocaleId.Pseudo);
        catalog.SetHeader("MIME-Version", "1.0");
        catalog.SetHeader("Content-Type", "text/plain; charset=UTF-8");
        catalog.SetHeader("Content-Transfer-Encoding", "8bit");
        catalog.SetHeader("Plural-Forms", "nplurals=2; plural=(n != 1);");
        catalog.SetHeader("X-Generator", "mf-l10n");
        foreach (var source in template.Messages)
        {
            if (source.Obsolete)
                continue;
            var entry = source.CloneTemplate();
            entry.References.Clear();
            entry.ExtractedComments.Clear();
            entry.Translations.Add(Transform(source.Id, charset, expansion));
            if (source.IdPlural is not null)
                entry.Translations.Add(Transform(source.IdPlural, charset, expansion));
            catalog.Entries.Add(entry);
        }

        return catalog;
    }

    public static PseudoCharset ParseCharset(string value) => value.ToLowerInvariant() switch
    {
        "full" => PseudoCharset.Full,
        "latin1" or "latin-1" => PseudoCharset.Latin1,
        _ => throw new ArgumentException($"unknown charset '{value}' (full, latin1)"),
    };

    public static double ParseExpansion(string value) =>
        double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var e) && e is >= 0 and <= 4
            ? e
            : throw new ArgumentException($"invalid expansion '{value}' (0..4, e.g. 0.3)");
}
