using System.Globalization;

namespace MainframeEngine.Localization;

/// <summary>
/// Locale names in gettext form (<c>pt_BR</c>, <c>zh_Hans_CN</c>), the form used for catalog folders
/// (<c>Content/locale/pt_BR/LC_MESSAGES/messages.mo</c>). Accepts .NET/BCP-47 names (<c>pt-BR</c>) and POSIX names
/// with an encoding or modifier (<c>pt_BR.UTF-8@euro</c>) and normalises them.
/// </summary>
public static class LocaleId
{
    /// <summary>The pseudo-locale generated by <c>mf-l10n pseudo</c> (accented, expanded, bracketed strings).</summary>
    public const string Pseudo = "qps";

    /// <summary>
    /// Canonical gettext form: language lowercase, a 4-letter script title-case, a region uppercase, joined with
    /// <c>_</c>. Encoding (<c>.UTF-8</c>) and modifier (<c>@euro</c>) suffixes are dropped. Returns an empty string
    /// for an empty or unusable name.
    /// </summary>
    public static string Normalize(string? locale)
    {
        if (string.IsNullOrWhiteSpace(locale))
            return string.Empty;

        var span = locale.AsSpan().Trim();
        var cut = span.IndexOfAny('.', '@');
        if (cut >= 0)
            span = span[..cut];
        if (span.IsEmpty)
            return string.Empty;

        Span<char> buffer = stackalloc char[Math.Min(span.Length, 64)];
        if (span.Length > buffer.Length)
            return string.Empty;

        var length = 0;
        var segment = 0;
        var segmentStart = 0;
        for (var i = 0; i <= span.Length; i++)
        {
            if (i < span.Length && span[i] is not ('_' or '-'))
                continue;

            var part = span[segmentStart..i];
            segmentStart = i + 1;
            if (part.IsEmpty)
                continue;
            foreach (var c in part)
            {
                if (!char.IsAsciiLetterOrDigit(c))
                    return string.Empty;
            }

            if (segment > 0)
                buffer[length++] = '_';
            for (var j = 0; j < part.Length; j++)
            {
                var c = part[j];
                buffer[length++] = segment == 0
                    ? char.ToLowerInvariant(c)
                    : part.Length == 4 ? (j == 0 ? char.ToUpperInvariant(c) : char.ToLowerInvariant(c))
                    : char.ToUpperInvariant(c);
            }

            segment++;
        }

        return length == 0 ? string.Empty : new string(buffer[..length]);
    }

    /// <summary>The .NET culture name for a locale (<c>pt_BR</c> → <c>pt-BR</c>).</summary>
    public static string ToCultureName(string locale) => Normalize(locale).Replace('_', '-');

    /// <summary>The language part of a locale (<c>pt_BR</c> → <c>pt</c>).</summary>
    public static string Language(string locale)
    {
        var normalized = Normalize(locale);
        var cut = normalized.IndexOf('_', StringComparison.Ordinal);
        return cut < 0 ? normalized : normalized[..cut];
    }

    /// <summary>
    /// The lookup chain for <paramref name="locale"/>: the locale, then each shorter parent (<c>zh_Hans_CN</c> →
    /// <c>zh_Hans</c> → <c>zh</c>), then <paramref name="fallbacks"/> (in order, each with its parents), then
    /// <paramref name="sourceLocale"/> (the language the msgids are written in). Duplicates are removed.
    /// </summary>
    public static IReadOnlyList<string> Chain(string locale, string sourceLocale, IEnumerable<string>? fallbacks = null)
    {
        var chain = new List<string>(4);
        AddWithParents(chain, Normalize(locale));
        if (fallbacks is not null)
        {
            foreach (var fallback in fallbacks)
                AddWithParents(chain, Normalize(fallback));
        }

        AddWithParents(chain, Normalize(sourceLocale));
        return chain;
    }

    private static void AddWithParents(List<string> chain, string locale)
    {
        while (locale.Length > 0)
        {
            if (!chain.Contains(locale, StringComparer.Ordinal))
                chain.Add(locale);
            var cut = locale.LastIndexOf('_');
            locale = cut < 0 ? string.Empty : locale[..cut];
        }
    }

    /// <summary>
    /// A <see cref="CultureInfo"/> for number and date formatting in <paramref name="locale"/>. The pseudo-locale and
    /// names .NET does not know fall back to the closest parent, then the invariant culture.
    /// </summary>
    public static CultureInfo GetCulture(string locale)
    {
        var normalized = Normalize(locale);
        if (normalized == Pseudo)
            return CultureInfo.GetCultureInfo("en");
        while (normalized.Length > 0)
        {
            try
            {
                return CultureInfo.GetCultureInfo(normalized.Replace('_', '-'));
            }
            catch (CultureNotFoundException)
            {
                var cut = normalized.LastIndexOf('_');
                normalized = cut < 0 ? string.Empty : normalized[..cut];
            }
        }

        return CultureInfo.InvariantCulture;
    }

    /// <summary>
    /// A name for language menus: the locale's own name (<c>español</c>, <c>português (Brasil)</c>), or
    /// <c>Pseudo-locale (qps)</c>; the locale id itself when .NET does not know it.
    /// </summary>
    public static string DisplayName(string locale)
    {
        var normalized = Normalize(locale);
        if (normalized == Pseudo)
            return "Pseudo-locale (qps)";
        var culture = GetCulture(normalized);
        return culture == CultureInfo.InvariantCulture || culture.Name.Length == 0 ? normalized : culture.NativeName;
    }

    /// <summary>The operating system's UI language in gettext form (<c>en_US</c>), or empty when it is invariant.</summary>
    public static string SystemLocale => Normalize(CultureInfo.CurrentUICulture.Name);
}
