<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <!-- NuGet Packages -->
    <ItemGroup>
        <PackageReference Include="ENet-CSharp" Version="2.4.8" />
        <PackageReference Include="ImGui.NET" Version="1.89.9.3" />
        <PackageReference Include="Silk.NET.Assimp" Version="2.21.0" />
        <PackageReference Include="Silk.NET.Input" Version="2.21.0" />
        <PackageReference Include="Silk.NET.Windowing" Version="2.21.0" />
        <PackageReference Include="Silk.NET.Vulkan" Version="2.22.0" />
        <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" Version="2.22.0" />
        <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.22.0" />
        <PackageReference Include="StbImageSharp" Version="2.30.15" />
        <PackageReference Include="Steamworks.NET" Version="2024.8.0" />
    </ItemGroup>
    
    <!-- Local References -->
    <ItemGroup>
      <ProjectReference Include="..\Plugins\Spine\spine-csharp\spine-csharp.csproj" />
    </ItemGroup>

    <!-- Copy everything in content folder to build destination -->
    <ItemGroup>
      <None Update="Content\**">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
